[package]
name = "cpubars"
version = "0.2.1"
authors = ["Douglas Campos"]
description = "shows cpu utilization by core in bars"
homepage = "https://github.com/qmx/cpubars"
repository = "https://github.com/qmx/cpubars"
license = "MIT/Apache-2.0"

[dependencies]
failure = "0.1.1"
clap = "2.30.0"
